version: "1.0"

services:
  main:
    build:
      context: .
      target: main-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      target: worker
    expose:
      - "4000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
